### ISSUE TITLE
crfsuite and liblbfgs need their lib folders for electron-rebuild success

### ISSUE THREAD

**Issue by AimForNaN** [vunb/node-crfsuite#8]
In order to be able to use this module in electron it needs to be rebuilt using electron-rebuild. However, because the dependencies do not have their lib directories (which contain all necessary header files, etc), electron-rebuild fails to rebuild node-crfsuite. It would be nice if node-crfsuite shipped with these folders or made where electron-rebuild does not fail.

**Comment by vunb** [comment]
Thank @truefusion I will add them in the next version. But i wish you can help a hand to make it soon to be present
